language: python
python:
- 3.6
install:
- pip install -r requirements.txt
- pip install pytest pytest-mock
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: vivarium
  password:
    secure: malIV+PHWxoBNz+0aXTfJxBbEqoROyAbAcklNTaxo+uvUv1rIoiEHwxdLHUvQ40vBV0DbitQsarPGQRrS4qD8OjSnHfwTyaHnlDlGvWC+tN/v1nPylbqIECVLPTcMcDF9E6OQDRDhu/g8aGn4lSI3u4MVHuo+LSsDOpDNdpw2GcTd66HwyBDaKAvTW1fcwm2B94GKk9V8TD+Czn3TFsuz5d9GoYUV9J7VGUmxA7pYpW2eyd74ohUJDMJ7Sp4Q+JOlHUTG7ri+TbVBGmKfMfCTYdhCporr20IRxadrUQwm5eEPLfuG4aCVhrBaZ/Kw6sdmG9fdxpR0+AuWDnzkQGY4668I98uxT3zXkxPMVhKU1ZMkSb9ofsKoHEPybrLUB14ho0ZqgHKrhE+zRJ6q071aQPxRYLzSibmjzqhedwqEQbf7cQHn+p9mhSd4ysPU3hQFyDsVb/X3hDHq+EAzWv5i+tUbGBgoiudO88Dgh3uuaZZdU7fqDGJcXb077L12gaxbrvKlt7D0nxDm9UDo6s/l1GM2wxkFTRbisdwh68uMqdOdjeEkPaBH+11zUbsGNfVRUAV6pk/HtQSpqFkORPkW2TZ5ZTLwKHo2PxT5Wl0y70fih5pUcKNJFNI163VPVCBc8Iz/VSuEc8E3FrkBirHiQM8+jv3iO+cfzgmzJmgDYk=
  on:
    distributions: sdist bdist_wheel
    repo: ihmeuw/vivarium
    tags: true
